const COUNTRY_NAMES = [
    "Algeria",
    "Andorra",
    "Antigua and Barbuda",
    "Afghanistan",
    "Anguilla",
    "Armenia",
    "Albania",
    "Angola",
    "Antarctica",
    "American Samoa",
    "Argentina",
    "Australia",
    "Austria",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bahrain",
    "Burundi",
    "Benin",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Bonaire, Saint Eustatius and Saba ",
    "Brazil",
    "Bahamas",
    "Belarus",
    "Belize",
    "British Indian Ocean Territory",
    "British Virgin Islands",
    "Croatia",
    "Cook Islands",
    "Colombia",
    "China",
    "Cameroon",
    "Chile",
    "Cocos Islands",
    "Canada",
    "Central African Republic",
    "Czech Republic",
    "Cyprus",
    "Christmas Island",
    "Costa Rica",
    "Curacao",
    "Cape Verde",
    "Cuba",
    "Cambodia",
    "Comoros",
    "Cayman Islands",
    "Chad",
    "Democratic Republic of the Congo",
    "Dominican Republic",
    "Dominica",
    "Djibouti",
    "Denmark",
    "East Timor",
    "Equatorial Guinea",
    "El Salvador",
    "Estonia",
    "Egypt",
    "Ecuador",
    "Ethiopia",
    "Eritrea",
    "French Guiana",
    "French Polynesia",
    "France",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Faroe Islands",
    "French Southern Territories",
    "Guinea-Bissau",
    "Guam",
    "Guatemala",
    "Greece",
    "Guadeloupe",
    "Guyana",
    "Guernsey",
    "Georgia",
    "Grenada",
    "Gabon",
    "Guinea",
    "Gambia",
    "Greenland",
    "Gibraltar",
    "Ghana",
    "Germany",
    "Haiti",
    "Hungary",
    "Hong Kong",
    "Honduras",
    "Heard Island and McDonald Islands",
    "Iraq",
    "Italy",
    "Isle of Man",
    "Israel",
    "Ivory Coast",
    "Iceland",
    "Iran",
    "India",
    "Ireland",
    "Indonesia",
    "Jamaica",
    "Jersey",
    "Japan",
    "Jordan",
    "Kosovo",
    "Kyrgyzstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kazakhstan",
    "Lebanon",
    "Laos",
    "Liechtenstein",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Liberia",
    "Lesotho",
    "Libya",
    "Montenegro",
    "Moldova",
    "Madagascar",
    "Morocco",
    "Monaco",
    "Myanmar",
    "Mali",
    "Macao",
    "Mongolia",
    "Marshall Islands",
    "Macedonia",
    "Mauritius",
    "Malta",
    "Malawi",
    "Maldives",
    "Martinique",
    "Montserrat",
    "Mauritania",
    "Malaysia",
    "Mexico",
    "Micronesia",
    "Mayotte",
    "Mozambique",
    "Northern Mariana Islands",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "New Zealand",
    "Nepal",
    "Nauru",
    "Niue",
    "North Korea",
    "Oman",
    "Puerto Rico",
    "Palestinian Territory",
    "Palau",
    "Portugal",
    "Paraguay",
    "Panama",
    "Papua New Guinea",
    "Peru",
    "Pakistan",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Qatar",
    "Russia",
    "Rwanda",
    "Reunion",
    "Romania",
    "Republic of the Congo",
    "Saint Barthelemy",
    "Samoa",
    "Serbia",
    "South Georgia and the South Sandwich Islands",
    "Svalbard and Jan Mayen",
    "Saint Pierre and Miquelon",
    "South Africa",
    "Solomon Islands",
    "Somalia",
    "Saudi Arabia",
    "Spain",
    "Saint Martin",
    "Saint Helena",
    "Switzerland",
    "Swaziland",
    "Syria",
    "Sint Maarten",
    "South Sudan",
    "Suriname",
    "Saint Kitts and Nevis",
    "Sao Tome and Principe",
    "Slovakia",
    "South Korea",
    "Slovenia",
    "Senegal",
    "San Marino",
    "Sierra Leone",
    "Seychelles",
    "Singapore",
    "Sweden",
    "Sudan",
    "Saint Lucia",
    "Sri Lanka",
    "Saint Vincent and the Grenadines",
    "Turkmenistan",
    "Tajikistan",
    "Tokelau",
    "Tunisia",
    "Tanzania",
    "Tuvalu",
    "Taiwan",
    "Trinidad and Tobago",
    "Turkey",
    "Tonga",
    "Thailand",
    "Togo",
    "Turks and Caicos Islands",
    "United Kingdom",
    "Uzbekistan",
    "Uganda",
    "USA",
    "Uruguay",
    "United States Minor Outlying Islands",
    "United Arab Emirates",
    "U.S. Virgin Islands",
    "Ukraine",
    "Venezuela",
    "Vietnam",
    "Vanuatu",
    "Vatican",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

export default COUNTRY_NAMES;
