export const COUNTRY_NAMES_ENG = [
    "Algeria",
    "Andorra",
    "Antigua and Barbuda",
    "Afghanistan",
    "Anguilla",
    "Armenia",
    "Albania",
    "Angola",
    "Antarctica",
    "American Samoa",
    "Argentina",
    "Australia",
    "Austria",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bahrain",
    "Burundi",
    "Benin",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Bonaire, Saint Eustatius and Saba ",
    "Brazil",
    "Bahamas",
    "Belarus",
    "Belize",
    "British Indian Ocean Territory",
    "British Virgin Islands",
    "Croatia",
    "Cook Islands",
    "Colombia",
    "China",
    "Cameroon",
    "Chile",
    "Cocos Islands",
    "Canada",
    "Central African Republic",
    "Czech Republic",
    "Cyprus",
    "Christmas Island",
    "Costa Rica",
    "Curacao",
    "Cape Verde",
    "Cuba",
    "Cambodia",
    "Comoros",
    "Cayman Islands",
    "Chad",
    "Democratic Republic of the Congo",
    "Dominican Republic",
    "Dominica",
    "Djibouti",
    "Denmark",
    "East Timor",
    "Equatorial Guinea",
    "El Salvador",
    "Estonia",
    "Egypt",
    "Ecuador",
    "Ethiopia",
    "Eritrea",
    "French Guiana",
    "French Polynesia",
    "France",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Faroe Islands",
    "French Southern Territories",
    "Guinea-Bissau",
    "Guam",
    "Guatemala",
    "Greece",
    "Guadeloupe",
    "Guyana",
    "Guernsey",
    "Georgia",
    "Grenada",
    "Gabon",
    "Guinea",
    "Gambia",
    "Greenland",
    "Gibraltar",
    "Ghana",
    "Germany",
    "Haiti",
    "Hungary",
    "Hong Kong",
    "Honduras",
    "Heard Island and McDonald Islands",
    "Iraq",
    "Italy",
    "Isle of Man",
    "Israel",
    "Ivory Coast",
    "Iceland",
    "Iran",
    "India",
    "Ireland",
    "Indonesia",
    "Jamaica",
    "Jersey",
    "Japan",
    "Jordan",
    "Kosovo",
    "Kyrgyzstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kazakhstan",
    "Lebanon",
    "Laos",
    "Liechtenstein",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Liberia",
    "Lesotho",
    "Libya",
    "Montenegro",
    "Moldova",
    "Madagascar",
    "Morocco",
    "Monaco",
    "Myanmar",
    "Mali",
    "Macao",
    "Mongolia",
    "Marshall Islands",
    "Macedonia",
    "Mauritius",
    "Malta",
    "Malawi",
    "Maldives",
    "Martinique",
    "Montserrat",
    "Mauritania",
    "Malaysia",
    "Mexico",
    "Micronesia",
    "Mayotte",
    "Mozambique",
    "Northern Mariana Islands",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "New Zealand",
    "Nepal",
    "Nauru",
    "Niue",
    "North Korea",
    "Oman",
    "Puerto Rico",
    "Palestinian Territory",
    "Palau",
    "Portugal",
    "Paraguay",
    "Panama",
    "Papua New Guinea",
    "Peru",
    "Pakistan",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Qatar",
    "Russia",
    "Rwanda",
    "Reunion",
    "Romania",
    "Republic of the Congo",
    "Saint Barthelemy",
    "Samoa",
    "Serbia",
    "South Georgia and the South Sandwich Islands",
    "Svalbard and Jan Mayen",
    "Saint Pierre and Miquelon",
    "South Africa",
    "Solomon Islands",
    "Somalia",
    "Saudi Arabia",
    "Spain",
    "Saint Martin",
    "Saint Helena",
    "Switzerland",
    "Swaziland",
    "Syria",
    "Sint Maarten",
    "South Sudan",
    "Suriname",
    "Saint Kitts and Nevis",
    "Sao Tome and Principe",
    "Slovakia",
    "South Korea",
    "Slovenia",
    "Senegal",
    "San Marino",
    "Sierra Leone",
    "Seychelles",
    "Singapore",
    "Sweden",
    "Sudan",
    "Saint Lucia",
    "Sri Lanka",
    "Saint Vincent and the Grenadines",
    "Turkmenistan",
    "Tajikistan",
    "Tokelau",
    "Tunisia",
    "Tanzania",
    "Tuvalu",
    "Taiwan",
    "Trinidad and Tobago",
    "Turkey",
    "Tonga",
    "Thailand",
    "Togo",
    "Turks and Caicos Islands",
    "United Kingdom",
    "Uzbekistan",
    "Uganda",
    "USA",
    "Uruguay",
    "United States Minor Outlying Islands",
    "United Arab Emirates",
    "U.S. Virgin Islands",
    "Ukraine",
    "Venezuela",
    "Vietnam",
    "Vanuatu",
    "Vatican",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

export const COUNTRY_NAMES_PL = [
    "Afganistan",
    "Albania",
    "Algieria",
    "Andora",
    "Angola",
    "Anguilla",
    "Antarktyka",
    "Antigua i Barbuda",
    "Arabia Saudyjska",
    "Argentyna",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbejdżan",
    "Bahamy",
    "Bahrajn",
    "Bangladesz",
    "Barbados",
    "Belgia",
    "Belize",
    "Benin",
    "Bermudy",
    "Bhutan",
    "Białoruś",
    "Boliwia",
    "Bośnia i Hercegowina",
    "Botswana",
    "Brazylia",
    "Brunei",
    "Brytyjskie Wyspy Dziewicze",
    "Brytyjskie Terytorium Oceanu Indyjskiego",
    "Bułgaria",
    "Burkina Faso",
    "Burundi",
    "Chiny",
    "Chile",
    "Chorwacja",
    "Cooka Wyspy",
    "Curacao",
    "Cypr",
    "Czad",
    "Czarnogóra",
    "Czechy",
    "Demokratyczna Republika Konga",
    "Dania",
    "Dominika",
    "Dominikana",
    "Dżibuti",
    "Egipt",
    "Ekwador",
    "Erytrea",
    "Estonia",
    "Eswatini",
    "Etiopia",
    "Falklandy",
    "Fidżi",
    "Filipiny",
    "Finlandia",
    "Francja",
    "Francuskie Terytoria Południowe",
    "Gabon",
    "Gambia",
    "Ghana",
    "Gibraltar",
    "Grecja",
    "Grenada",
    "Grenlandia",
    "Gruzia",
    "Guam",
    "Gujana",
    "Gwadelupa",
    "Gwatemala",
    "Gwinea",
    "Gwinea Bissau",
    "Gwinea Równikowa",
    "Haiti",
    "Hiszpania",
    "Holandia",
    "Honduras",
    "Hongkong",
    "Indie",
    "Indonezja",
    "Irak",
    "Iran",
    "Irlandia",
    "Islandia",
    "Izrael",
    "Jamajka",
    "Japonia",
    "Jemen",
    "Jersey",
    "Jordania",
    "Kajmany",
    "Kambodża",
    "Kamerun",
    "Kanada",
    "Katar",
    "Kazachstan",
    "Kenia",
    "Kirgistan",
    "Kiribati",
    "Kolumbia",
    "Komory",
    "Kongo",
    "Korea Południowa",
    "Korea Północna",
    "Kosowo",
    "Kostaryka",
    "Kuba",
    "Kuwejt",
    "Laos",
    "Lesotho",
    "Liban",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Litwa",
    "Luksemburg",
    "Łotwa",
    "Macedonia Północna",
    "Madagaskar",
    "Majotta",
    "Makau",
    "Malawi",
    "Malediwy",
    "Malezja",
    "Mali",
    "Malta",
    "Mariany Północne",
    "Maroko",
    "Martynika",
    "Mauretania",
    "Mauritius",
    "Meksyk",
    "Mikronezja",
    "Mołdawia",
    "Monako",
    "Mongolia",
    "Montserrat",
    "Mozambik",
    "Mjanma",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niemcy",
    "Niger",
    "Nigeria",
    "Nikaragua",
    "Niue",
    "Norfolk",
    "Norwegia",
    "Nowa Kaledonia",
    "Nowa Zelandia",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestyna",
    "Panama",
    "Papua-Nowa Gwinea",
    "Paragwaj",
    "Peru",
    "Pitcairn",
    "Polska",
    "Portoryko",
    "Portugalia",
    "Republika Środkowoafrykańska",
    "Republika Zielonego Przylądka",
    "Reunion",
    "Rosja",
    "Rumunia",
    "Rwanda",
    "Sahara Zachodnia",
    "Saint Barthelemy",
    "Saint Kitts i Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre i Miquelon",
    "Saint Vincent i Grenadyny",
    "Salwador",
    "Samoa",
    "San Marino",
    "Senegal",
    "Serbia",
    "Seszele",
    "Sierra Leone",
    "Singapur",
    "Sint Maarten",
    "Słowacja",
    "Słowenia",
    "Somalia",
    "Sri Lanka",
    "Stany Zjednoczone",
    "Suazi",
    "Sudan",
    "Surinam",
    "Svalbard i Jan Mayen",
    "Syria",
    "Szwajcaria",
    "Szwecja",
    "Tadżykistan",
    "Tajlandia",
    "Tajwan",
    "Tanzania",
    "Timor Wschodni",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trynidad i Tobago",
    "Tunezja",
    "Turcja",
    "Turkmenistan",
    "Turks i Caicos",
    "Uganda",
    "Ukraina",
    "Urugwaj",
    "Uzbekistan",
    "Vanuatu",
    "Watykan",
    "Wenezuela",
    "Węgry",
    "Wielka Brytania",
    "Wietnam",
    "Włochy",
    "Wspólnota Dominiki",
    "Wybrzeże Kości Słoniowej",
    "Wyspa Bożego Narodzenia",
    "Wyspa Bouveta",
    "Wyspa Man",
    "Wyspa Świętej Heleny",
    "Wyspy Alandzkie",
    "Wyspy Cooka",
    "Wyspy Heard i McDonalda",
    "Wyspy Marshalla",
    "Wyspy Owcze",
    "Wyspy Salomona",
    "Zambia",
    "Zimbabwe",
    "Zjednoczone Emiraty Arabskie",
    "Zjednoczone Stany Mniejsze Odległe"
];

export const getCountryNames = (lang: string): string[] => {
    return lang === "pl" ? COUNTRY_NAMES_PL : COUNTRY_NAMES_ENG;
};
